export const LIST_ALARM_SUCCESS = "LIST_ALARM_SUCCESS";
export const LIST_ALARM_PAST_SUCCESS = "LIST_ALARM_PAST_SUCCESS";

export const SET_ALARM_LOADING = "SET_ALARM_LOADING";
export const SET_ALARM_LOADING_ERROR = "SET_ALARM_LOADING_ERROR";
