export const LIST_CUSTOMER_SUCCESS = "LIST_CUSTOMER_SUCCESS";
export const LIST_CUSTOMER_SUCCESS_SEARCH = "LIST_CUSTOMER_SUCCESS_SEARCH";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const CUSTOMER_CHECKBOX_UPDATE = "CUSTOMER_CHECKBOX_UPDATE";

export const SET_CUSTOMER_LOADING = "SET_CUSTOMER_LOADING";
export const SET_CUSTOMER_LOADING_ERROR = "SET_CUSTOMER_LOADING_ERROR";
