export const LIST_DASHBOARD_SUCCESS = "LIST_DASHBOARD_SUCCESS";

export const SET_DASHBOARD_LOADING = "SET_DASHBOARD_LOADING";
export const SET_DASHBOARD_LOADING_ERROR = "SET_DASHBOARD_LOADING_ERROR";
