export const LIST_DEVICE_SUCCESS = "LIST_DEVICE_SUCCESS";
export const CREATE_DEVICE_SUCCESS = "CREATE_DEVICE_SUCCESS";
export const UPDATE_DEVICE_SUCCESS = "UPDATE_DEVICE_SUCCESS";
export const DELETE_DEVICE_SUCCESS = "DELETE_DEVICE_SUCCESS";
export const ASSIGN_DEVICE_SUCCESS = "ASSIGN_DEVICE_SUCCESS";

export const SET_DEVICE_LOADING = "SET_DEVICE_LOADING";
export const SET_DEVICE_LOADING_ERROR = "SET_DEVICE_LOADING_ERROR";
