export const LIST_DRIVER_SUCCESS = "LIST_DRIVER_SUCCESS";
export const CREATE_DRIVER_SUCCESS = "CREATE_DRIVER_SUCCESS";
export const UPDATE_DRIVER_SUCCESS = "UPDATE_DRIVER_SUCCESS";
export const DELETE_DRIVER_SUCCESS = "DELETE_DRIVER_SUCCESS";
export const DRIVER_CHECKBOX_UPDATE = "DRIVER_CHECKBOX_UPDATE";
export const LIST_DRIVER_SUCCESS_SEARCH = "LIST_DRIVER_SUCCESS_SEARCH"

export const SET_DRIVER_LOADING = "SET_DRIVER_LOADING";
export const SET_DRIVER_LOADING_ERROR = "SET_DRIVER_LOADING_ERROR";
