export const GET_MAP_DATA = "GET_MAP_DATA";

export const GET_MAP_DATA_LOADING = "GET_MAP_DATA_LOADING";
export const GET_MAP_DATA_ERROR = "GET_MAP_DATA_ERROR";

export const GET_MAP_DATA_DEVICE = "GET_MAP_DATA_DEVICE";

export const GET_MAP_DATA_LOADING_DEVICE = "GET_MAP_DATA_LOADING_DEVICE";
export const GET_MAP_DATA_ERROR_DEVICE = "GET_MAP_DATA_ERROR_DEVICE";
