export const LIST_NOTIFICATIONS_SUCCESS = "LIST_NOTIFICATIONS_SUCCESS";

export const SET_NOTIFICATIONS_LOADING = "SET_NOTIFICATIONS_LOADING";
export const SET_NOTIFICATIONS_LOADING_ERROR = "SET_NOTIFICATIONS_LOADING_ERROR";
