export const LIST_SOILTABLE_SUCCESS = "LIST_SOILTABLE_SUCCESS";
export const SET_SOILTABLE_LOADING = "SET_SOILTABLE_LOADING";
export const SET_SOILTABLE_ERROR = "SET_SOILTABLE_ERROR";
export const CREATE_SOILTABLE = "CREATE_SOILTABLE";
export const UPDATE_SOILTABLE_SUCCESS = "UPDATE_SOILTABLE_SUCCESS";
export const APPROVE_SOILTABLE_SUCCESS = "APPROVE_SOILTABLE_SUCCESS";
