export const LIST_TRUCK_SUCCESS = "LIST_TRUCK_SUCCESS";
export const CREATE_TRUCK_SUCCESS = "CREATE_TRUCK_SUCCESS";
export const UPDATE_TRUCK_SUCCESS = "UPDATE_TRUCK_SUCCESS";
export const DELETE_TRUCK_SUCCESS = "DELETE_TRUCK_SUCCESS";
export const TRUCK_CHECKBOX_UPDATE = "TRUCK_CHECKBOX_UPDATE";
export const LIST_TRUCK_SUCCESS_SEARCH = "LIST_TRUCK_SUCCESS_SEARCH";

export const SET_TRUCK_LOADING = "SET_TRUCK_LOADING";
export const SET_TRUCK_LOADING_ERROR = "SET_TRUCK_LOADING_ERROR";
