export const LIST_UNIT_SUCCESS = "LIST_UNIT_SUCCESS";
export const CREATE_UNIT_SUCCESS = "CREATE_UNIT_SUCCESS";
export const UPDATE_UNIT_SUCCESS = "UPDATE_UNIT_SUCCESS";
export const DELETE_UNIT_SUCCESS = "DELETE_UNIT_SUCCESS";
