export const eventData = [
  { eventType: 6, eventName: "Slave-lock lock" },
  { eventType: 12, eventName: "Device offline" },
  { eventType: 17, eventName: "Charging" },
  { eventType: 18, eventName: "Maintenance" },
  { eventType: 19, eventName: "Press button" },
  { eventType: 20, eventName: "Pull out lock rope" },
  { eventType: 31, eventName: "Open door" },
  { eventType: 32, eventName: "Close door" },
  { eventType: 46, eventName: "Leave the starting point" },
  { eventType: 47, eventName: "Reach the destination" },
  { eventType: 48, eventName: "Leave the destination" },
  { eventType: 49, eventName: "Complete the waybill" },
  { eventType: 50, eventName: "Entry waypoint" },
  { eventType: 41, eventName: "Leave waypoint" },
  { eventType: 1, eventName: "Speeding Alarm" },
  { eventType: 40, eventName: "Lock rope cut" },
  { eventType: 41, eventName: "Vibration" },
  { eventType: 42, eventName: "Long-time unlocking" },
  { eventType: 43, eventName: "Unlock password error for 5 consecutive times" },
  { eventType: 44, eventName: "Swiping illegal RFID card" },
  { eventType: 45, eventName: "Low power" },
  { eventType: 46, eventName: "Back cover opened" },
  { eventType: 47, eventName: "Motor stuck" },
  { eventType: 48, eventName: "Enter fence alarm" },
  { eventType: 49, eventName: "Exit fence alarm" },
  { eventType: 193, eventName: "Lock device abnormal" },
  { eventType: 194, eventName: "Unlock password error" },
  { eventType: 195, eventName: "Do not perform unlocking without positioning" },
  { eventType: 196, eventName: "No unlocking outside the fence" },
  { eventType: 198, eventName: "Slave sensor signal lost" },
  { eventType: 403, eventName: "Out fence unlock" },
  { eventType: 63, eventName: "Temperature alert" },
  { eventType: 316, eventName: "Light sensor alarm" },
];
export const alarmEventData = [
  { eventType: 1, eventName: "High temperature alarm" },
  { eventType: 2, eventName: "Low temperature alarm" },
  { eventType: 3, eventName: "High humidity alarm" },
  { eventType: 4, eventName: "Low humidity alarm" },
  { eventType: 5, eventName: "High light" },
  { eventType: 6, eventName: "Low light" },
  { eventType: 7, eventName: "High air pressure" },
  { eventType: 8, eventName: "Low air pressure" },
];
